---
title: "DownstreamAnalysis"
output: html_document
date: "2024-10-04"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(ggplot2)
library(DESeq2)
library(tidyverse)
library(dplyr)
library(ggrepel)
library(pheatmap)
```

```{r}
# load count matrix and SRA run table for meta-info
count_matrix_tpm <- read.csv('/Users/luisabender/Studium/Praktische Arbeit/count_matrix.csv', row.names = 1)
count_matrix_tpm <- count_matrix[, order(colnames(count_matrix))]
count_matrix_raw <- read.csv('/Users/luisabender/Studium/Praktische Arbeit/count_matrix_raw.csv', row.names = 1)
count_matrix_raw <- count_matrix_raw[, order(colnames(count_matrix_raw))]


sra_runtable <- read.csv('/Users/luisabender/Studium/Praktische Arbeit/SraRunTable.txt', row.names = 1)
sra_runtable <- sra_runtable[sra_runtable$treatment == "untreated" | sra_runtable$treatment == "Fusarium oxysporum 5176",]

# meta info with days post treatment, and treatment
meta_info <- sra_runtable[, -c(1:27,30)]
meta_info <- meta_info[rownames(meta_info) != "SRR13824038",]
meta_info$days_post_treatment <- factor(meta_info$days_post_treatment)
```

### Counting reads

```{r}
total_reads_per_sample <- colSums(count_matrix_raw)
total_reads_per_sample_df <- data.frame(sample = names(total_reads_per_sample), total_counts = total_reads_per_sample)

# merge with metadata
total_reads_per_sample_meta <- merge(total_reads_per_sample_df, meta_info2, by.x = "sample", by.y = "Sample_ID")

total_reads_per_gene <- rowSums(count_matrix_raw)
total_reads_per_gene_df <- data.frame(gene = names(total_reads_per_gene), total_counts = total_reads_per_gene)
sorted_gene_counts <- sort(total_reads_per_gene, decreasing = TRUE)
top_20_genes <- head(sorted_gene_counts, 20)
top_20_genes_df <- data.frame(top_20_genes,gene = names(top_20_genes), counts = top_20_genes)


# visualize counts
#heatmap_data <- as.matrix(total_reads_per_sample)
#pheatmap(heatmap_data, cluster_rows = FALSE, main = "Heatmap of Total Read Counts per Sample")
ggplot(total_reads_per_sample_meta, aes(sample, total_counts, fill = treatment)) +
  geom_bar(stat="identity", position=position_dodge(width = 5)) +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))

ggplot(top_20_genes_df, aes(gene, counts)) + geom_bar(stat="identity") +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))

```


### Run VST with raw count matrix

```{r}
# create DESeqDataSet
dds <- DESeqDataSetFromMatrix(countData = round(count_matrix_raw), 
                              colData = meta_info, 
                              design = ~ treatment + days_post_treatment)


#variance stabilization transformation with DESeqDataSet
vst <- vst(dds)

# vst with count matrix
#vst_counts <- varianceStabilizingTransformation(count_matrix_raw, blind = TRUE, fitType = "parametric")
#getVarianceStabilizedData(object)

```

### Run PCA with tpm counts

```{r}
meta_info2 <- meta_info
meta_info2$Sample_ID <- row.names(meta_info2)
# log transform the tpm counts
log_count_matrix_tpm <- log2(count_matrix_tpm + 1)

# perform PCA 
pca_result_tpm <- prcomp(t(log_count_matrix_tpm))

# Extract the PCA coordinates
pca_data <- data.frame(Sample = rownames(pca_result_tpm$x),
                       PC1 = pca_result_tpm$x[, 1], 
                       PC2 = pca_result_tpm$x[, 2], 
                       PC3 = pca_result_tpm$x[, 3])

# Combine with metadata
pca_data <- merge(pca_data, meta_info2, by.x = "Sample", by.y = "Sample_ID")

# mark potential outliers
outliers <- pca_data[abs(pca_data$PC1) > 250 | abs(pca_data$PC2) > 150, ]

ggplot(pca_data, aes(x = PC1, y = PC2, color = treatment)) +
    geom_point() +
    stat_ellipse(aes(color = treatment), type = "norm", linetype = 2) +
    stat_ellipse(type = "t") +
    geom_text_repel(data = outliers, aes(label = Sample), vjust = -1, hjust = 1.1, color = "black") +
    xlab(paste0("PC1: ", round(100 * summary(pca_result_tpm)$importance[2, 1], 2), "% variance")) +
    ylab(paste0("PC2: ", round(100 * summary(pca_result_tpm)$importance[2, 2], 2), "% variance")) +
    ggtitle("PCA with data ellipses") +
    theme_minimal()

ggplot(pca_data, aes(x = PC1, y = PC2, color = days_post_treatment, shape = treatment)) +
    geom_point() +
    stat_ellipse(aes(color = treatment), type = "norm") +
    geom_text_repel(data = outliers, aes(label = Sample), vjust = -1, hjust = 1.1, color = "black") +
    xlab(paste0("PC1: ", round(100 * summary(pca_result_tpm)$importance[2, 1], 2), "% variance")) +
    ylab(paste0("PC2: ", round(100 * summary(pca_result_tpm)$importance[2, 2], 2), "% variance")) +
    ggtitle("PCA with data ellipses") +
    theme_minimal()

# include PC3
ggplot(pca_data, aes(x = PC2, y = PC3, color = days_post_treatment, shape = treatment)) +
    geom_point() +
    stat_ellipse(aes(color = treatment), type = "norm") +
    geom_text_repel(data = outliers, aes(label = Sample), vjust = -1, hjust = 1.1, color = "black") +
    xlab(paste0("PC2: ", round(100 * summary(pca_result_tpm)$importance[2, 2], 2), "% variance")) +
    ylab(paste0("PC3: ", round(100 * summary(pca_result_tpm)$importance[2, 3], 2), "% variance")) +
    ggtitle("PCA with data ellipses") +
    theme_minimal()

```


```{r pressure, echo=FALSE}
# for plots without showing the code
plot(pressure)
```


