---
title: "Data cleaning & preprocessing"
output: html_document
date: "2025-01-27"
---
```{r}
library(WGCNA)
```

```{r}
# load expression data
options(stringsAsFactors = FALSE)
expr_data <- read.csv("~/Studium/bachelor-thesis-luisa/count_tables/vst_expression_data.csv", row.names = 1)

# transpose it for WGCNA
input_mat <- t(expr_data)
```

```{r}
gsg = goodSamplesGenes(input_mat, verbose = 3)
gsg$allOK # TRUE
summary(gsg)
```

```{r}
# Identifying outlier samples
sampleTree <- hclust(dist(input_mat), method = "average") #Clustering samples based on distance 

#Setting the graphical parameters
par(cex = 0.6);
par(mar = c(0,4,2,0))

#Plotting the cluster dendrogram
plot(sampleTree, main = "Sample clustering to detect outliers", sub="", xlab="", cex.lab = 1.5,
cex.axis = 1.5, cex.main = 2)
```

Loading meta data:
```{r}
# loading meta data
metaData <- read.csv("~/Studium/bachelor-thesis-luisa/data/metaData.csv", sep=";")
metaData$Timepoint_dpi <- metaData$Timepoint..dpi.

# create pathogen column
metaData$pathogen <- ifelse(metaData$Experiment == "Heterodera schachtii 2", "Heterodera schachtii", metaData$Experiment)
metaData$pathogen <- ifelse(metaData$Experiment == "Hyaloperonospora arabidopsidis 3", "Hyaloperonospora arabidopsidis", metaData$pathogen)
metaData$pathogen <- ifelse(metaData$Experiment == "Plasmodiophora brassicae 2", "Plasmodiophora brassicae", metaData$pathogen)
metaData$pathogen <- ifelse(metaData$Experiment == "Turnip mosaic virus (TuMV) 3", "Turnip mosaic virus (TuMV)", metaData$pathogen)

# get pathogen abbreviations
metaData$pathogen_abbr <- ifelse(metaData$pathogen == "Heterodera schachtii", "H. schachtii", metaData$pathogen)
metaData$pathogen_abbr <- ifelse(metaData$pathogen == "Alternaria brassicae", "A. brassicae", metaData$pathogen_abbr)
metaData$pathogen_abbr <- ifelse(metaData$pathogen == "Botrytis cinerea", "B. cinerea", metaData$pathogen_abbr)
metaData$pathogen_abbr <- ifelse(metaData$pathogen == "Cauliflower mosaic virus (CaMV)", "CaMV", metaData$pathogen_abbr)
metaData$pathogen_abbr <- ifelse(metaData$pathogen == "Turnip mosaic virus (TuMV)", "TuMV", metaData$pathogen_abbr)
metaData$pathogen_abbr <- ifelse(metaData$pathogen == "Turnip yellows virus (TuYV)", "TuYV", metaData$pathogen_abbr)
metaData$pathogen_abbr <- ifelse(metaData$pathogen == "Turnip yellows virus (TuYV)", "TuYV", metaData$pathogen_abbr)
metaData$pathogen_abbr <- ifelse(metaData$pathogen == "Golovinomyces orontii", "G. orontii", metaData$pathogen_abbr)
metaData$pathogen_abbr <- ifelse(metaData$pathogen == "Erysiphe cichoracearum ", "E. cichoracearum", metaData$pathogen_abbr) 	
metaData$pathogen_abbr <- ifelse(metaData$pathogen == "Hyaloperonospora arabidopsidis", "Hpa", metaData$pathogen_abbr)
metaData$pathogen_abbr <- ifelse(metaData$pathogen == "Meloidogyne javanica", "M. javanica", metaData$pathogen_abbr)
metaData$pathogen_abbr <- ifelse(metaData$pathogen == "Plasmodiophora brassicae", "P. brassicae", metaData$pathogen_abbr)

# column with infected pathogens (take all control samples together)
metaData$inf_path <- ifelse(metaData$infected_control == "infected", metaData$pathogen_abbr, "control")

# coumn with infected pathogens in category
metaData$Category <- ifelse(metaData$infected_control == "infected", metaData$Category, "control")
metaData$Category_trophs <- ifelse(metaData$infected_control == "infected", metaData$Category_trophs, "control")

# create binary meta data for correlation calculations
metaData_bin <- binarizeCategoricalColumns(metaData, convertColumns = c("inf_path", "infected_control", "Timepoint..dpi.", "Library", "Category", "Category_trophs"), includePairwise = FALSE, includeLevelVsAll = TRUE, minCount = 1, dropFirstLevelVsAll = FALSE)
colnames(metaData_bin) <- gsub(".vs.all", "", colnames(metaData_bin))

# remove CaMV category (unsure)
metaData_bin <- metaData_bin[,-35]
```

```{r}
# only numerical meta Data
metData <- metaData_bin[, -c(1,2,3)]

sampleTree2 <- hclust(dist(input_mat), method = "average")

metaColors <- numbers2colors(metaData_bin[, grep("inf_path", colnames(metaData_bin))], signed = FALSE)
options(repr.plot.width = 20, repr.plot.height = 20,repr.res = 200)
plotDendroAndColors(sampleTree2, metaColors, groupLabels = names(metaData_bin[, grep("inf_path", colnames(metaData_bin))])%>% gsub("inf_path.", "", .), main = "Sample dendrogram and metadata heatmap")

metaColors_sub_cat <- numbers2colors(metaData_bin[, grep("Category\\.", colnames(metaData_bin))], signed = FALSE)
options(repr.plot.width = 20, repr.plot.height = 20,repr.res = 200)
plotDendroAndColors(sampleTree2, metaColors_sub_cat, groupLabels = names(metaData_bin[, grep("Category\\.", colnames(metaData_bin))])%>% gsub("Category\\.", "", .), main = "Sample dendrogram and metadata heatmap")

```


